version: '3.5'
networks:
  default:
    external:
      name: gateway
  mysql:
    driver: bridge
    internal: true

services:
  website:
    image: southcaws/tobyobart:latest
    restart: on-failure
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:www.tobyob.art,tobyob.art
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.SSLHost=www.tobyob.art
      - traefik.frontend.redirect.regex=^https?://[a-z0-9.]+/(.*)
      - traefik.frontend.redirect.replacement=https://www.tobyob.art/$${1}
      - com.centurylinklabs.watchtower.enable=true
